server:
  port: 80
spring:
  application:
    name: meihua_music
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://180.76.100.99:3306/music?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true
    username: root
    password: 1234
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: music

#  config:
#    import: optional:file:.env[.yml]


#微信小程序
weixin:
  mp:
    app-id: wxd757380b82913aff
    app-secret: c33e59d4fe83df510f14ec3592d43de7