server:
  port: 80
spring:
  application:
    name: meihua_music
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://180.76.100.99:3306/music?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1234
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: music

#  config:
#    import: optional:file:.env[.yml]
