server:
  port: 9001
spring:
  application:
    name: meihua_music
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://180.76.100.99:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1234
  jpa:
    database: mysql
    show-sql: true
